version: '3.3'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    container_name: shortened-urls-db
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQLDB_ROOT_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    expose:
      - $MYSQLDB_LOCAL_PORT
    volumes:
      - shortened-urls-db:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    expose:
      - ${REDIS_LOCAL_PORT}
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD

  app:
    depends_on:
      - db
      - redis
    build: ../
    container_name: url-shortener-api
    restart: unless-stopped
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    env_file: ./.env
    environment:
      DB_HOST: db
      DB_PORT: $MYSQLDB_LOCAL_PORT
      DB_NAME: $MYSQLDB_DATABASE
      DB_USER: $MYSQLDB_USER
      DB_PASSWORD: $MYSQLDB_PASSWORD
      SERVER_PORT: $SPRING_LOCAL_PORT
      REDIS_HOST: redis
      REDIS_PORT: $REDIS_LOCAL_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
      CACHE_TYPE: $CACHE_TYPE
      CACHE_TTL: $CACHE_TTL
      RETENTION_PERIOD: $RETENTION_PERIOD
      BASE_URL: $BASE_URL
    volumes:
      - .m2:/root/.m2

volumes:
  shortened-urls-db: